-- 코드를 입력하세요
SELECT COUNT(DISTINCT NAME) 
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;

-- 코드를 입력하세요
SELECT COUNT(*) FROM (SELECT DISTINCT AI.NAME FROM ANIMAL_INS AI WHERE AI.NAME IS NOT NULL) AS SUBQUERY;